import { Itinerary } from "@/components/types";

export function generateICS(itinerary: Itinerary): string {
  const lines: string[] = [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//Wanderlust//Trip Planner//EN",
    "CALSCALE:GREGORIAN",
  ];

  const startDate = new Date();
  startDate.setDate(startDate.getDate() + 1);

  itinerary.itinerary.forEach((day) => {
    const dayDate = new Date(startDate);
    dayDate.setDate(startDate.getDate() + day.day - 1);
    const dateStr = dayDate.toISOString().replace(/[-:]/g, "").split(".")[0];

    day.places.forEach((place) => {
      const timeMap: Record<string, { start: string; end: string }> = {
        morning: { start: "090000", end: "120000" },
        afternoon: { start: "130000", end: "170000" },
        evening: { start: "180000", end: "210000" },
      };
      const time = timeMap[place.time] || timeMap.morning;
      const dayPrefix = dateStr.substring(0, 8);

      lines.push("BEGIN:VEVENT");
      lines.push(`DTSTART:${dayPrefix}T${time.start}`);
      lines.push(`DTEND:${dayPrefix}T${time.end}`);
      lines.push(`SUMMARY:${place.name}`);
      lines.push(`DESCRIPTION:Day ${day.day} - ${place.time} activity for ${itinerary.destination}`);
      if (place.lat && place.lon) {
        lines.push(`GEO:${place.lat};${place.lon}`);
      }
      lines.push(`LOCATION:${place.name}`);
      lines.push("END:VEVENT");
    });
  });

  lines.push("END:VCALENDAR");
  return lines.join("\r\n");
}

export function downloadICS(itinerary: Itinerary) {
  const ics = generateICS(itinerary);
  const blob = new Blob([ics], { type: "text/calendar;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `wanderlust-${itinerary.destination.replace(/\s+/g, "-").toLowerCase()}.ics`;
  a.click();
  URL.revokeObjectURL(url);
}

export async function downloadPDF(itinerary: Itinerary) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF();
  const margin = 20;
  let y = margin;
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text(`Trip to ${itinerary.destination}`, margin, y);
  y += 10;

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(`${itinerary.days} days | ${itinerary.budget} budget`, margin, y);
  y += 12;

  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  itinerary.itinerary.forEach((day) => {
    if (y > 260) {
      doc.addPage();
      y = margin;
    }

    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 30, 30);
    doc.text(`Day ${day.day}`, margin, y);
    y += 8;

    day.places.forEach((place) => {
      if (y > 270) {
        doc.addPage();
        y = margin;
      }

      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(60, 60, 60);
      const timeLabel = place.time.charAt(0).toUpperCase() + place.time.slice(1);
      doc.text(`${timeLabel}`, margin + 4, y);

      doc.setFont("helvetica", "normal");
      doc.setTextColor(30, 30, 30);
      doc.text(place.name, margin + 30, y);
      y += 6;

      if (place.type) {
        doc.setFontSize(8);
        doc.setTextColor(120, 120, 120);
        doc.text(place.type, margin + 30, y);
        y += 5;
      }

      y += 2;
    });

    y += 6;
  });

  doc.setFontSize(8);
  doc.setTextColor(160, 160, 160);
  doc.text("Generated by Wanderlust — AI Travel Planner", margin, 290);

  doc.save(`wanderlust-${itinerary.destination.replace(/\s+/g, "-").toLowerCase()}.pdf`);
}
